- name: mysql
  hosts: filepath
  become: true
  become_user: root
  tasks:
#    - name: copy test
#      copy:
#        src: "/var/lib/awx/projects/*zyz"
#        dest: "/usr/local/service-center/docker/zyz222"
    - name: git test
      git:
        accept_hostkey: yes
        version: V1.0
        remote: get@192.168.0.168
        executable: /usr/bin/git
        repo: git@192.168.0.168:java/business/government/wc-xcb/zyzpt.git
        dest: /usr/local/peoject/
        force: yes
        key_file: /root/.ssh/id_rsa


