- name: mysql
  hosts: filepath
  become: true
  become_user: root
  tasks:
    - name: copy test
      copy:
        src: "/var/lib/awx/projects/*zyz"
        dest: "/usr/local/service-center/docker/zyz222"

