- name: mysql
  hosts: filepath
  become: true
  become_user: root
  tasks:
#    - name: copy test
#      copy:
#        src: "/var/lib/awx/projects/*zyz"
#        dest: "/usr/local/service-center/docker/zyz222"
    - name: git test
      git:
        remote: "zyz"
        repo: "git@192.168.0.168:java/business/government/wc-xcb/zyzpt.git"
        key_file: "/root/.ssh/id_rsa"
        dest: "/usr/local/peoject/zyz"
        accept_hostkey: yes
        version: "V1.0"
        executable: /usr/bin/git
        force: yes



