- name: mysql
  hosts: filepath
  become: true
  become_user: root
  tasks:
    - name: file
      file:
        path: "/usr/local/service-center/docker/{{path}}"

        state: directory
        mode: 777
        recurse: yes
    - name: template
      template: src="/docker-compose/docker-compose.tmp.j2" dest="/usr/local/service-center/docker/{{path}}/docker-compose.tmp"
#      备份
#      backup=yes
    - name: copy file
      copy:
        src: "/dockersh/"
        dest: "/usr/local/service-center/docker/{{path}}"
        mode: +x
- name: mysql
  hosts: filepath(201服务器上)
  become: true
  become_user: root
  tasks:
    - name: maven package
      shell: "mvn package"
    - name: mven

