- name: mysql
  hosts: filepath
  become: true
  become_user: root
  tasks:
#    - name: copy test
#      copy:
#        src: "/var/lib/awx/projects/*zyz"
#        dest: "/usr/local/service-center/docker/zyz222"
    - name: remove
      shell: rm -r /usr/local/peoject/zyz
#    - name: git test\
#      shell: /usr/bin/git clone --origin origin git@192.168.0.168:lml/testsshkeyclone.git  /usr/local/peoject/zyz
#      git: repo="git@192.168.0.168:java/business/government/wc-xcb/zyzpt.git" key_file=/root/.ssh/id_rsa_git dest=/usr/local/peoject/zyz clone=yes clone=yes update=yes version=master executable=/usr/bin/git force=yes
    - name: git test
#      shell: "/usr/bin/git clone --origin origin git@github.com:liulong2/test.git  /usr/local/peoject/zyz"
#      git: repo="git@github.com:liulong2/test.git" key_file=/root/.ssh/id_rsa_144 dest=/usr/local/peoject/zyz clone=yes clone=yes update=yes version=master executable=/usr/bin/git force=yes
      git:
        repo: "https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/liulong2/xingyv.git"
#        repo: "https://github.com/liulong2/xingyv.git"
        dest: /usr/local/peoject/lllzzz
#        version: master
      #        remote: "testsshkeyclone"
      #        accept_hostkey: yes
#/usr/bin/git clone --origin origin git@192.168.0.168:lml/testsshkeyclone.git  /usr/local/peoject/zyz


