---
- name: mysql
  hosts: mysql3
  become: true
  tasks:
    #解决 pip安装时报错
    - name: yum clean all
      shell: "yum clean all"
    - name: yum clean all
      shell: "rpm --rebuilddb"
#    - name: upgrade all packages
#      yum:
#        name: "*"
#        state: latest
    - name: yum remove
      shell: "yum remove epel-release"
    - name: yum -y install epel-release
      yum:
        name: epel-release;
        state: latest
    - name: installed pip
      yum:
        name: python-pip
        state: latest
    - name: MySQL-python
      #      yum:
      #        name: MySQL-python
      #      #        state: installed
      #        state: installed
      pip:
        name: MySQL-python
    - name: dump a database
      mysql_db:
        login_host: 192.168.0.206
        login_user: root
        login_password: "root"
        login_port: 3306
        name: all
        target: /tmp/mezz$(date +%Y-%m-%d).sql
        state: "dump"
    - name: fetch
      fetch:
        dest: /tmp/
        src: /tmp/mezz.sql

