---
- name: mysql
  hosts: mysql3
  become: true
  vars:
    packages: mysql-devel
    #      - mariadb
    #      - mariadb-server
    devle: MySQL-python

  tasks:
    - name: yum weget
      yum:
        name: wget
        state: installed
    - name: yum weget
      yum:
        name: setup
        state: installed
    - name: yum weget
      yum:
        name: perl
        state: installed

    - name: weget
      shell: "wget -P /usr/local/yum http://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/mysql57-community-release-el7-10.noarch.rpm"
    #        state: installed
    #        shell: "wget: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm"
    - name: rpm
      shell: chdir=/usr/local/yum  executeble="rpm -ivh mysql57-community-release-el7-10.noarch.rpm"

    - name: update Mysql
      yum:
        name: mysql-community-server
        state: installed

    - name: Installed mysql-devel
      yum:
        name: mysql-devel
        state: present
    #解决 pip安装时报错
    - name: weget pip
      shell: "wget -P /usr/local/yum http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm"
    # 第一次执行时需要进行安装
    #    - name: rpm pip install
    #      shell: "rpm -ivh http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm"
    - name: rpm pip
      shell: chdir=/usr/local/yum  executeble="rpm -ivh epel-release-6-8.noarch.rpm"

    #解决 pip安装时报错
    - name: rpm pip bug
      shell: "wget -P /usr/local/yum http://www.percona.com/redir/downloads/Percona-XtraDB-Cluster/5.5.37-25.10/RPM/rhel6/x86_64/Percona-XtraDB-Cluster-shared-55-5.5.37-25.10.756.el6.x86_64.rpm"
    - name: rpm
      shell: chdir=/usr/local/yum  executeble="rpm -ivh Percona-XtraDB-Cluster-shared-55-5.5.37-25.10.756.el6.x86_64.rpm"

    - name: update yum
      shell: "yum update"

    - name: installed pip
      yum:
        name: python-pip
        state: installed

    - name: update pip
      shell: "pip install --upgrade pip"
    #      pip:
    #        name: upgrade
    #        state: latest

    - name: python-devel
      yum:
        name: python-devel
        state: installed

    - name: gcc
      yum:
        name: gcc
        state: installed
    #      shell: "yum install gcc"

    - name: MySQL-python
      #      yum:
      #        name: MySQL-python
      #      #        state: installed
      #        state: installed
      pip:
        name: MySQL-python

    - name: dump a database
      mysql_db:
        login_host: 192.168.0.206
        login_user: root
        login_password: "root"
        login_port: 3306
        name: all
        target: /tmp/mezz.sql
        state: "dump"
    - name: fetch
      fetch:
        dest: /tmp/
        src: /tmp/mezz$(date +%Y-%m-%d).sql
