---
- name: mysql
  hosts: mysql3
  become: true
  vars:
    packages: mysql-devel
      #      - mariadb
    #      - mariadb-server
    devle: MySQL-python

  tasks:
    - name: yum weget
      yum:
        name: wget
        state: installed
    - name: yum weget
      yum:
        name: setup
        state: installed
    - name: yum weget
      yum:
        name: perl
        state: installed

    - name: weget
      shell: "wget -P /usr/local/yum http://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/mysql57-community-release-el7-10.noarch.rpm"
#        state: installed
#        shell: "wget: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm"
    - name: rpm
      shell: chdir=/usr/local/yum  executeble="rpm mysql-community-release-el7-5.noarch.rpm"
    - name: update Mysql
      yum:
        name: mysql-community-server
        state: installed

    - name: Installed mysql-devel
      yum:
        name: mysql-devel
        state: present

    - name: installed pip
      yum:
        name: python-pip
        state: installed

    - name: update pip
      shell: "pip install --upgrade pip"
#      pip:
#        name: upgrade
#        state: latest

    - name: devel
      yum:
        name: python-devel
        state: installed
    - name: gcc
      shell: "yum install gcc python-devel"

    - name: MySQL-python
#      yum:
#        name: MySQL-python
#      #        state: installed
#        state: installed
      pip:
        name: MySQL-python

    - name: dump a database
      mysql_db:
        login_host: 192.168.188.142
        login_user: root
        login_password: "root"
        login_port: 3306
        name: all
        target: /tmp/mezz.sql
        state: "dump"
    - name: fetch
      fetch:
        dest: /tmp/
        src: /tmp/mezz.sql