---
- name: mysql
  hosts: mysql3
  become: true
  tasks:
    #解决 pip安装时报错
    - name: weget pip
      shell: "wget -P /usr/local/yum http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm"
    # 第一次执行时需要进行安装
    #    - name: rpm pip install
    #      shell: "rpm -ivh http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm"
    - name: rpm pip
      shell: chdir=/usr/local/yum  executeble="rpm -ivh epel-release-6-8.noarch.rpm"
    - name: update yum
      yum:
        name: update
    - name: update yum
      shell: "yum -y install epel-release"
#    - name: update yum
#      shell: "yum install -y python-pip"

#    #解决 pip安装时报错
#    - name: rpm pip bug
#      shell: "wget -P /usr/local/yum http://www.percona.com/redir/downloads/Percona-XtraDB-Cluster/5.5.37-25.10/RPM/rhel6/x86_64/Percona-XtraDB-Cluster-shared-55-5.5.37-25.10.756.el6.x86_64.rpm"
#    - name: rpm
#
#      shell: chdir=/usr/local/yum  executeble="rpm -ivh Percona-XtraDB-Cluster-shared-55-5.5.37-25.10.756.el6.x86_64.rpm"
#    - name: installed pip
      yum:
        name: python-pip
        state: installed
    - name: MySQL-python
      #      yum:
      #        name: MySQL-python
      #      #        state: installed
      #        state: installed
      pip:
        name: MySQL-python
    - name: dump a database
      mysql_db:
        login_host: 192.168.0.206
        login_user: root
        login_password: "root"
        login_port: 3306
        name: all
        target: /tmp/mezz$(date +%Y-%m-%d).sql
        state: "dump"
    - name: fetch
      fetch:
        dest: /tmp/
        src: /tmp/mezz.sql

