---
- name: mysql
  hosts: mysql3
  vars:
    packages:
      setup: filter=ansible_all_ipv4_addresses

  tasks:
    #解决 pip安装时报错
#    - name: yum clean all
#      shell: "yum clean all"
#    - name: yum clean all
#      shell: "rpm --rebuilddb"
##    - name: upgrade all packages
##      yum:
##        name: "*"
##        state: latest
#    - name: yum remove epel-release
#      yum:
#        name: epel-release
#        state: removed
#暂时注释
#    - name: yum -y install epel-release
#      shell: "yum -y install epel-release"
#    - name: installed pip
#      yum:
#        name: python-pip
#        state: latest
#    - name: update pip
#      shell: "pip install --upgrade pip"
#
#
#    - name: weget
#      shell: "wget -P /usr/local/yum http://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/mysql57-community-release-el7-10.noarch.rpm"
#        #        state: installed
#        #        shell: "wget: http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm"
#    - name: rpm
#      shell: chdir=/usr/local/yum  executeble="rpm -ivh mysql57-community-release-el7-10.noarch.rpm"
#
#    - name: Installed mysql-devel
#      yum:
#        name: mysql-devel
#        state: present
#
#    - name: gcc
#      yum:
#        name: gcc
#        state: installed
#  #      shell: "yum install gcc"
#    - name: MySQL-python
#      #      yum:
#      #        name: MySQL-python
#      #      #        state: installed
#      #        state: installed
#      pip:
#        name: MySQL-python


    - name: dump a database
      mysql_db:
        login_host: "{{group_names}}"
        login_user: root
        login_password: "root"
        login_port: 3306
        name: all
        target: /tmp/mezz1.gz
        state: "dump"
#      loop: "{{packages}}"
#    - name: fetch
#      - shell: "scp -r root@{{packages}}:/tmp/mezz1.gz  /tmp/{{packages}}"
#      fetch:
#        dest: /tmp/
#        src: /tmp/mezz1.gz
#    - name: dump a database
#      mysql_db:
#        login_host: 192.168.0.207
#        login_user: root
#        login_password: "root"
#        login_port: 3306
#        name: all
#        target: /tmp/mezz.sql
#        state: "dump"
#    - name: fetch
#      fetch:
#        dest: /tmp/
#        src: /tmp/mezz.sql
