---
- name: mysql
  hosts: mysql3
  become: true
  tasks:
    - name: rpm pip install
        shell: "rpm -ivh http://dl.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm"
    - name: installed pip
      yum:
        name: python-pip
        state: installed
    - name: MySQL-python
      #      yum:
      #        name: MySQL-python
      #      #        state: installed
      #        state: installed
      pip:
        name: MySQL-python
    - name: dump a database
      mysql_db:
        login_host: 192.168.0.206
        login_user: root
        login_password: "root"
        login_port: 3306
        name: all
        target: /tmp/mezz$(date +%Y-%m-%d).sql
        state: "dump"
    - name: fetch
      fetch:
        dest: /tmp/
        src: /tmp/mezz.sql

